[shlvl]
disabled = false
format = 'SHLVL\($shlvl\) '
threshold = 3

[shell]
disabled = false

[directory]
fish_style_pwd_dir_length = 5

[status]
disabled = false

[sudo]
disabled = false

[direnv]
disabled = false

[env_var.PRESET_MODE]
format = "\nMOD: [$env_value]($style) "
style = "bold dimmed yellow"

[env_var.CUBRID]
format = "CUB: [$env_value]($style) "
style = "bold dimmed yellow"

[custom.gcc]
description = "Show GCC version"
command = "gcc --version | head -n 1 | awk '{print $1 $3}'"
detect_files = ['CMakeLists.txt']
style = "green"

[custom.clang]
description = "Show Clang version"
command = "clang --version | head -n 1 | awk '{print $1 $3}'"
detect_files = ['CMakeLists.txt']
style = "green"

[os]
disabled = false

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
