[manager]
show_hidden = true
sort_by = "mtime"
sort_dir_first = false
sort_reverse = true
linemode = "mtime"

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"
